//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventoryApp.i18n {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyInventoryApp.i18n.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UnitNameLabel {
            get {
                return ResourceManager.GetString("UnitNameLabel", resourceCulture);
            }
        }
        
        public static string UnitAbbrLabel {
            get {
                return ResourceManager.GetString("UnitAbbrLabel", resourceCulture);
            }
        }
        
        public static string UnitTypeLabel {
            get {
                return ResourceManager.GetString("UnitTypeLabel", resourceCulture);
            }
        }
        
        public static string UnitTypeVolumeLabel {
            get {
                return ResourceManager.GetString("UnitTypeVolumeLabel", resourceCulture);
            }
        }
        
        public static string UnitTypeMassLabel {
            get {
                return ResourceManager.GetString("UnitTypeMassLabel", resourceCulture);
            }
        }
        
        public static string UnitTypeAreaLabel {
            get {
                return ResourceManager.GetString("UnitTypeAreaLabel", resourceCulture);
            }
        }
        
        public static string CommodityNameLabel {
            get {
                return ResourceManager.GetString("CommodityNameLabel", resourceCulture);
            }
        }
        
        public static string CommodityAltNameLabel {
            get {
                return ResourceManager.GetString("CommodityAltNameLabel", resourceCulture);
            }
        }
        
        public static string CommodityBarcodeLabel {
            get {
                return ResourceManager.GetString("CommodityBarcodeLabel", resourceCulture);
            }
        }
        
        public static string CommodityUnitValueWeightLabel {
            get {
                return ResourceManager.GetString("CommodityUnitValueWeightLabel", resourceCulture);
            }
        }
        
        public static string CommodityUnitValueSizeLabel {
            get {
                return ResourceManager.GetString("CommodityUnitValueSizeLabel", resourceCulture);
            }
        }
        
        public static string CommodityUnitValueAreaLabel {
            get {
                return ResourceManager.GetString("CommodityUnitValueAreaLabel", resourceCulture);
            }
        }
        
        public static string CommodityUnitLabel {
            get {
                return ResourceManager.GetString("CommodityUnitLabel", resourceCulture);
            }
        }
        
        public static string CommodityPriceLabel {
            get {
                return ResourceManager.GetString("CommodityPriceLabel", resourceCulture);
            }
        }
        
        public static string CommodityNotesLabel {
            get {
                return ResourceManager.GetString("CommodityNotesLabel", resourceCulture);
            }
        }
        
        public static string CommodityImagesLabel {
            get {
                return ResourceManager.GetString("CommodityImagesLabel", resourceCulture);
            }
        }
        
        public static string NewButton {
            get {
                return ResourceManager.GetString("NewButton", resourceCulture);
            }
        }
        
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        public static string SyncronizeButton {
            get {
                return ResourceManager.GetString("SyncronizeButton", resourceCulture);
            }
        }
        
        public static string CommoditiesTitle {
            get {
                return ResourceManager.GetString("CommoditiesTitle", resourceCulture);
            }
        }
        
        public static string UnitsTitle {
            get {
                return ResourceManager.GetString("UnitsTitle", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
    }
}
